# Copyright (c) Facebook, Inc. and its affiliates.

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

version: '3'

volumes:
  whatsappMedia:
    driver: local
  postgresData:
    driver: local

services:
  db:
    image: postgres
    command: "-p 5432 -N 500"
    #command: "psql -p 33060 -U root"
    restart: always
    environment:
      POSTGRES_PASSWORD: testpass
      PGPASSWORD: testpass
      POSTGRES_USER: root
    expose:
        - "54320"
    ports:
        - "5432:5432"
    volumes:
     - postgresData:/var/lib/postgresql/data
    network_mode: bridge
    cap_drop:
      - MKNOD
  wacore:
    image: docker.whatsapp.biz/coreapp:v2.39.1
    command: ["/opt/whatsapp/bin/wait_on_postgres.sh", "/opt/whatsapp/bin/launch_within_docker.sh"]
    volumes:
     - whatsappMedia:/usr/local/wamedia
    env_file:
      - db.env
    environment:
      # This is the version of the docker templates being used to run WhatsApp Business API
      WA_RUNNING_ENV_VERSION: v2.2.3
      WA_WEB_SERVERNAME: 172.18.0.1
      ORCHESTRATION: DOCKER-COMPOSE
    depends_on:
      - "db"
    network_mode: bridge
    links:
      - db
    cap_drop:
      - MKNOD
  waweb:
    image: docker.whatsapp.biz/web:v2.39.1
    command: ["/opt/whatsapp/bin/wait_on_postgres.sh", "/opt/whatsapp/bin/launch_within_docker.sh"]
    ports:
     - "9090:443"
    volumes:
     - whatsappMedia:/usr/local/wamedia
    env_file:
      - db.env
    environment:
      WACORE_HOSTNAME: wacore
      # This is the version of the docker templates being used to run WhatsApp Business API
      WA_RUNNING_ENV_VERSION: v2.2.3
      #This is the server where API get install
      WA_WEB_SERVERNAME: 172.18.0.1
      ORCHESTRATION: DOCKER-COMPOSE
    depends_on:
      - "db"
      - "wacore"
    links:
      - db
      - wacore
    network_mode: bridge
    cap_drop:
      - MKNOD
